name: Docker Image CI

on:
  push:
    branches: ['master']
  create:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-shanghai.aliyuncs.com # 镜像容器服务的登录地址
        region-id: cn-shanghai
        username: "${{ secrets.ALI_REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.ALI_REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
    
    - name: Build the Docker image
      run: |
        docker build --file ./docker/Dockerfile.latest --tag registry.cn-shanghai.aliyuncs.com/qn-open/chatgpt-on-wechat:20240116 . 
        docker push registry.cn-shanghai.aliyuncs.com/qn-open/chatgpt-on-wechat:20240116
